# -*- coding: utf-8 -*-
"""Support Vector Machine(Wine Quality).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3uf3_4_3pSno_vbssQETvtdhbWldzwQ

Using the Wine Quality dataset from Kaggle, develop a Python program to implement a Support Vector Machine (SVM) for classifying wine samples into quality categories (good or bad). Load and explore the dataset, perform necessary preprocessing such as handling missing values and feature scaling, and split the data into training and testing sets. Train SVM models using different kernels (linear, polynomial, and RBF), evaluate their performance using appropriate metrics like accuracy and confusion matrix, and analyze which kernel provides the best classification performance.
"""

#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Importing dataset
df=pd.read_csv('/content/WineQT.csv')

df.head()

df.shape

#Identifing the dataset
df.info()

df.describe()

# Feature distribution
df.hist(figsize=(12,10))
plt.suptitle("Feature Distributions")
plt.show()

#Check the presence of Missing values
df.isnull().sum()

"""There are no missing values in the dataset"""

#Removinbg unnessasary columns
df = df.drop(columns=['Id'])

"""Removing the columns that dont affect the model."""

df.head()

# Convert quality into binary classification
# Good (1) if quality >= 7, else Bad (0)
df['quality_label'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

# Drop original quality column
df.drop('quality', axis=1, inplace=True)

"""First line - creates target labels (0 or 1)

Second line - removes old column to avoid confusion

We convert the quality column into a binary label where wines with quality ≥ 7 are marked as ‘good’ (1) and others as ‘bad’ (0), so that it becomes suitable for classification. Then we remove the original quality column to avoid redundancy and keep only the target label for the model.
"""

#Defining target and feature
X = df.drop('quality_label', axis=1)
y = df['quality_label']

#Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Feature scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""We perform feature scaling to bring all input features to the same scale, because SVM is distance-based and features with larger values can dominate the model. Scaling ensures fair contribution from all features and improves model accuracy.

# Train SVM Models with Different Kernels

Linear is simple, polynomial handles moderate complexity, and RBF is best for complex non-linear data.
"""

#Linear Kernal
svm_linear = SVC(kernel='linear')
svm_linear.fit(X_train, y_train)

y_pred_linear = svm_linear.predict(X_test)

"""Linear kernel is used when data can be separated with a straight line."""

#Polynomial kernal
svm_poly = SVC(kernel='poly')
svm_poly.fit(X_train, y_train)

y_pred_poly = svm_poly.predict(X_test)

"""Polynomial kernel handles non-linear data by creating curved boundaries."""

#RBF Kernal
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train, y_train)

y_pred_rbf = svm_rbf.predict(X_test)

"""RBF kernel maps data into higher dimensions to handle complex patterns."""

#Reussable Heatmap Function
def plot_confusion_matrix(cm, title):
    plt.figure()
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(title)
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

"""#Model Evaluation

1) Linear Kernal
"""

#Accuracy(Linear kernal)
print("Accuracy:", accuracy_score(y_test, y_pred_linear))

"""THe Model has 87% accuracy"""

#Confution Matrix(Linear Kernal)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_linear))

"""The linear kernel model predicts only the majority class (bad wine), resulting in zero true positives. This indicates poor performance for detecting good quality wines, likely due to class imbalance or non-linear data."""

#Confution matrix Heatmap
cm_linear = confusion_matrix(y_test, y_pred_linear)
plot_confusion_matrix(cm_linear, "SVM Linear Kernel Confusion Matrix")

#Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred_linear))

"""The model performs well for the majority class (bad wine) but completely fails to classify the minority class (good wine). Although accuracy is high, it is misleading due to class imbalance, making the model unreliable.

2. Polynomial Kernal
"""

#Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_poly))

"""The model attains 89% accuracy"""

#Confution Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_poly))

"""he polynomial kernel improves performance compared to the linear kernel by correctly identifying some good wines, but it still has a high number of misclassifications, especially false negatives."""

cm_poly = confusion_matrix(y_test, y_pred_poly)
plot_confusion_matrix(cm_poly, "SVM Polynomial Kernel Confusion Matrix")

#Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred_poly))

"""The polynomial kernel improves the model by identifying some good quality wines, unlike the linear kernel. However, recall for the minority class is still low, meaning many good wines are misclassified. Overall, it performs better but is not optimal.

3.RBC Kernal
"""

#Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_rbf))

"""The Model attain 89% of accuracy"""

#Confution Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rbf))

"""The RBF kernel performs similarly to the polynomial kernel, correctly identifying some good wines but still misclassifying many. It shows balanced performance but does not significantly outperform the polynomial kernel in this case."""

cm_rbf = confusion_matrix(y_test, y_pred_rbf)
plot_confusion_matrix(cm_rbf, "SVM RBF Kernel Confusion Matrix")

#Classifacation Report
print("Classification Report:\n", classification_report(y_test, y_pred_rbf))

"""The RBF kernel shows similar performance to the polynomial kernel, with high accuracy for the majority class but low recall for the minority class. It slightly improves precision but still fails to correctly identify many good wines."""

# Store metrics
results = {
    'Linear': {'TP': 0, 'Recall_1': 0.00},
    'Polynomial': {'TP': 9, 'Recall_1': 0.32},
    'RBF': {'TP': 8, 'Recall_1': 0.29}
}

# Compare based on Recall (important for minority class)
best_kernel = max(results, key=lambda x: results[x]['Recall_1'])

print("Kernel Comparison (based on Recall for Good Wine):")
for k, v in results.items():
    print(f"{k}: TP = {v['TP']}, Recall = {v['Recall_1']}")

print("\nBest Kernel:", best_kernel)

"""Linear kernel performs poorly as it predicts only the majority class. Polynomial and RBF kernels perform better, with polynomial slightly outperforming RBF in detecting good wines. Overall, polynomial kernel is the best for this dataset.

#New prediction sample data
"""

# Example new wine data (replace with real values)
new_sample = [[7.4, 0.70, 0.00, 1.9, 0.076, 11, 34, 0.9978, 3.51, 0.56, 9.4]]

# Scale it (IMPORTANT!)
new_sample_scaled = scaler.transform(new_sample)

prediction = svm_rbf.predict(new_sample_scaled)

print("Prediction:", "Good Wine" if prediction[0] == 1 else "Bad Wine ")

"""represents a wine with:

Moderate acidity
High sulphates & alcohol not very high
Typical of lower quality wines (< 7)

So the model predicts:
 Class 0 → Bad Wine

The Support Vector Machine (SVM) models were trained using three different kernels: Linear, Polynomial, and RBF. Their performances were evaluated using accuracy, confusion matrix, and classification report.

The Linear kernel performed poorly as it predicted only the majority class (bad wine) and failed to identify any good quality wines, making it unsuitable for this dataset.

The Polynomial kernel showed significant improvement by capturing non-linear relationships in the data. It was able to correctly identify some good quality wines and achieved better recall and F1-score for the minority class.

The RBF kernel also handled non-linear data effectively and produced performance similar to the polynomial kernel. However, it slightly underperformed compared to the polynomial kernel in detecting good wines.
"""